name: Run Intercom Report Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # every minute UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Intercom Report Script
        run: python intercom_report.py
